/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tracker;

import org.gradle.testfixtures.ProjectBuilder;
import org.gradle.api.Project;
import org.gradle.api.Task;
import org.gradle.internal.impldep.org.testng.annotations.Test;

/**
 * A simple unit test for the 'tracker.greeting' plugin.
 */
class TrackerPluginTest {
    @Test void pluginRegistersATask() {
        // Create a test project and apply the plugin
        Project project = ProjectBuilder.builder().build();
        project.getPlugins().apply("tracker.greeting");

        // Verify the result
        assertNotNull(project.getTasks().findByName("greeting"));
    }

    private void assertNotNull(Task findByName) {
    }
}
